# Generated by Django 5.2.17 on 2026-09-09 18:46

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, null=True, srid=4326, verbose_name="зона"
                    ),
                ),
                (
                    "heatmap",
                    models.JSONField(
                        default=dict, verbose_name="тепловая карта, GeoJSON"
                    ),
                ),
                (
                    "direction_deg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="вектор движения, градусы"
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(auto_now=True, verbose_name="посчитано"),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_zone",
                        to="reports.lostreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "зона поиска",
                "verbose_name_plural": "зоны поиска",
            },
        ),
        migrations.CreateModel(
            name="Sighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "geog",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="точка"
                    ),
                ),
                ("seen_at", models.DateTimeField(verbose_name="когда видели")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("device_gps", "Геолокация устройства"),
                            ("manual_pin", "Точка на карте"),
                        ],
                        max_length=16,
                        verbose_name="источник точки",
                    ),
                ),
                (
                    "animal_in_custody",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="животное у меня"
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dog", "Собака"),
                            ("cat", "Кошка"),
                            ("bird", "Птица"),
                            ("other", "Другое"),
                        ],
                        max_length=16,
                        verbose_name="вид",
                    ),
                ),
                (
                    "colors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        default=list,
                        size=None,
                        verbose_name="окрас",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("sure", "Уверен"),
                            ("maybe", "Возможно"),
                            ("unsure", "Не уверен"),
                        ],
                        default="maybe",
                        max_length=16,
                        verbose_name="уверенность",
                    ),
                ),
                ("weight", models.FloatField(default=0.0, verbose_name="вес")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "Видна"),
                            ("hidden", "Скрыта"),
                            ("spam", "Спам"),
                        ],
                        db_index=True,
                        default="visible",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sightings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sightings",
                        to="reports.lostreport",
                        verbose_name="объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "отметка о наблюдении",
                "verbose_name_plural": "отметки о наблюдениях",
                "ordering": ("-seen_at",),
            },
        ),
        migrations.CreateModel(
            name="SightingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="sightings/%Y/%m/", verbose_name="фото"
                    ),
                ),
                (
                    "exif_stripped",
                    models.BooleanField(default=False, verbose_name="EXIF вырезан"),
                ),
                (
                    "sighting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="sightings.sighting",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото отметки",
                "verbose_name_plural": "фото отметок",
            },
        ),
        migrations.AddIndex(
            model_name="sighting",
            index=models.Index(
                fields=["report", "-seen_at"], name="sighting_report_seen_idx"
            ),
        ),
    ]
