# Generated by Django 5.2.17 on 2026-09-24 12:46

import apps.core.storage
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sightings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sightingphoto",
            name="exif_geog",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                null=True,
                srid=4326,
                verbose_name="точка из EXIF",
            ),
        ),
        migrations.AddField(
            model_name="sightingphoto",
            name="original",
            field=models.FileField(
                blank=True,
                storage=apps.core.storage.quarantine_storage,
                upload_to="sightings/%Y/%m/",
                verbose_name="исходник в карантине",
            ),
        ),
        migrations.AddField(
            model_name="sightingphoto",
            name="sha256",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="SHA-256 опубликованной копии"
            ),
        ),
        migrations.AddField(
            model_name="sightingphoto",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает обработки"),
                    ("published", "Опубликовано"),
                    ("rejected", "Отклонено"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="статус обработки",
            ),
        ),
        migrations.AlterField(
            model_name="sightingphoto",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="sightings/%Y/%m/", verbose_name="фото"
            ),
        ),
    ]
