# Generated by Django 5.2.17 on 2026-09-09 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                ("action", models.CharField(max_length=64, verbose_name="действие")),
                (
                    "target_repr",
                    models.CharField(max_length=255, verbose_name="объект"),
                ),
                ("note", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mod_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "действие модератора",
                "verbose_name_plural": "лог модерации",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AbuseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Спам или реклама"),
                            ("fake", "Фейковая отметка"),
                            ("extortion", "Вымогательство"),
                            ("abuse", "Оскорбления"),
                            ("other", "Другое"),
                        ],
                        max_length=16,
                        verbose_name="причина",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="разобрано"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abuse_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_abuse_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "жалоба",
                "verbose_name_plural": "жалобы",
                "ordering": ("resolved_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="abuse_target_idx"
                    )
                ],
            },
        ),
    ]
