# Generated by Django 5.2.17 on 2026-09-09 18:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(verbose_name="последний раз видели"),
                ),
                (
                    "last_seen_geog",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="точка пропажи"
                    ),
                ),
                (
                    "location_precision",
                    models.CharField(
                        choices=[("exact", "Точная"), ("blurred", "Смещённая")],
                        default="blurred",
                        max_length=16,
                        verbose_name="публичная точность",
                    ),
                ),
                (
                    "search_radius_m",
                    models.PositiveIntegerField(
                        default=2000, verbose_name="радиус поиска, м"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активно"),
                            ("found", "Найдено"),
                            ("archived", "Архив"),
                            ("hidden", "Скрыто модератором"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "reward_text",
                    models.TextField(blank=True, verbose_name="вознаграждение"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="pets.pet",
                        verbose_name="животное",
                    ),
                ),
            ],
            options={
                "verbose_name": "объявление о пропаже",
                "verbose_name_plural": "объявления о пропаже",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "active")),
                        fields=["last_seen_geog"],
                        name="lostreport_geog_active_gix",
                    )
                ],
            },
        ),
    ]
