# Generated by Django 5.2.17 on 2026-09-09 18:46

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="название"
                    ),
                ),
                (
                    "geog",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="центр"
                    ),
                ),
                (
                    "radius_m",
                    models.PositiveIntegerField(default=1500, verbose_name="радиус, м"),
                ),
                (
                    "species_filter",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("dog", "Собака"),
                                ("cat", "Кошка"),
                                ("bird", "Птица"),
                                ("other", "Другое"),
                            ],
                            max_length=16,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="фильтр по видам",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активна"
                    ),
                ),
                (
                    "quiet_from_hour",
                    models.PositiveSmallIntegerField(
                        default=22, verbose_name="тихие часы с"
                    ),
                ),
                (
                    "quiet_to_hour",
                    models.PositiveSmallIntegerField(
                        default=9, verbose_name="тихие часы до"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "гео-подписка",
                "verbose_name_plural": "гео-подписки",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "event_key",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="ключ события"
                    ),
                ),
                (
                    "delivered",
                    models.BooleanField(default=False, verbose_name="доставлено"),
                ),
                (
                    "suppressed_reason",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="почему не отправлено"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.geosubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
            },
        ),
        migrations.AddIndex(
            model_name="geosubscription",
            index=models.Index(
                condition=models.Q(("active", True)),
                fields=["geog"],
                name="geosub_geog_active_gix",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["user", "-created_at"], name="notiflog_user_created_idx"
            ),
        ),
    ]
