# Generated by Django 5.2.17 on 2026-09-09 18:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=64, verbose_name="кличка"),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "Собака"),
                            ("cat", "Кошка"),
                            ("bird", "Птица"),
                            ("other", "Другое"),
                        ],
                        max_length=16,
                        verbose_name="вид",
                    ),
                ),
                (
                    "breed",
                    models.CharField(blank=True, max_length=128, verbose_name="порода"),
                ),
                (
                    "colors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        default=list,
                        size=None,
                        verbose_name="окрас",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Маленькое"),
                            ("medium", "Среднее"),
                            ("large", "Крупное"),
                        ],
                        max_length=16,
                        verbose_name="размер",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Самец"),
                            ("female", "Самка"),
                            ("unknown", "Неизвестно"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="пол",
                    ),
                ),
                ("features", models.TextField(blank=True, verbose_name="приметы")),
                (
                    "chip_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        verbose_name="номер чипа",
                    ),
                ),
                (
                    "brand_number",
                    models.CharField(blank=True, max_length=32, verbose_name="клеймо"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "животное",
                "verbose_name_plural": "животные",
            },
        ),
        migrations.CreateModel(
            name="PetPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="pets/%Y/%m/", verbose_name="фото"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="основное"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото животного",
                "verbose_name_plural": "фото животных",
                "ordering": ("-is_primary", "created_at"),
            },
        ),
    ]
